/**
 * InSync Profiles — Licence Key System (v2 — Worker KV validation)
 *
 * Keys are validated by calling the Cloudflare Worker's /validate-key endpoint,
 * which checks the key's SHA-256 hash against the KV store (SYNC_EDITOR_KEYS).
 *
 * Every key generated by the PayPal IPN Worker is automatically stored in KV,
 * so no manual hash management or app rebuilds are needed for new purchases.
 *
 * Flow:
 *   1. User enters key → normalise → POST to /validate-key
 *   2. Worker hashes the key and checks KV → returns { valid: true/false }
 *   3. If valid, store the normalised hash in localStorage so the device
 *      stays unlocked without a network call on every visit.
 *   4. On subsequent visits, isLicenceActivated() checks localStorage first.
 *      If the stored hash is not in the legacy list, it re-validates online
 *      once per session to confirm the key hasn't been revoked.
 *
 * Legacy hardcoded hashes are kept so existing activated devices are not
 * locked out during the transition.
 */

// ── Legacy hardcoded hashes (existing activated users — do not remove) ────────
const LEGACY_KEY_HASHES: string[] = [
  // Demo keys
  "7c3d69e37d11fef62d2a0ce21a2a811a2f018b54c8bf8fd1a899649621e05ee6",
  "ec9dac2ed0fbb8e25a890142c3b3aeceedecb13fa1b3fff0a85da43ef720a37f",
  // Buyer keys (pre-KV era)
  "493a743555685c48dd34f76bc1cf6e384f16a8d39890e69f256897857ba8f035", // nadzak3434@gmail.com — SKI-2026-5401
  "2ceab9a2434c62ed3d7e5af55fad3d8ff6c817f3622d77db8713f6d51ff58951", // sarapumpd6@gmail.com — SKI-2026-7823
  // Legacy (with-hyphen hashes)
  "a3b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
  "60c65cd292d8c279a16e84b52362ef252921e625cc05ed2d6397c96411384ecd",
  "bdd22b55266b0a1066b80d0550d561687a092095f3a1ff6c23ca874e2686e542",
  "800568101d3ef987269e964600d66d04a7059bb111732202e392789485cd4c1e",
  "b42ae14d0edeab593016a835a39c9f0c9d74abdc9cdbf443d6b9eb037731eb14",
  "8841c21388df11b6175c039ad94839b0a14f64f7c552954ce838eb8aab07fbfd",
];

const STORAGE_KEY = "insync_licence_activated";
const STORAGE_KEY_RAW = "insync_licence_key_raw"; // stores normalised plain key for re-validation

/** Normalise a key: strip hyphens and spaces, then uppercase */
function normaliseKey(text: string): string {
  return text.trim().replace(/[\s-]/g, "").toUpperCase();
}

/** Hash a string using the browser's native SubtleCrypto API */
export async function sha256(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(normaliseKey(text));
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
}

/** Validate a key against the Worker's /validate-key KV endpoint */
async function validateKeyOnline(key: string): Promise<boolean> {
  try {
    const res = await fetch("/validate-key", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ key: normaliseKey(key) }),
    });
    if (!res.ok) return false;
    const data = await res.json();
    return data.valid === true;
  } catch {
    return false;
  }
}

/** Check if this device already has a valid activated licence */
export function isLicenceActivated(): boolean {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) return false;
    // Legacy hardcoded hashes — always valid
    if (LEGACY_KEY_HASHES.includes(stored)) return true;
    // KV-era keys: stored as "kv:<normalisedKey>" — treat as activated
    // (re-validation happens async in activateLicence on next entry)
    if (stored.startsWith("kv:")) return true;
    return false;
  } catch {
    return false;
  }
}

/** Validate a key entered by the user and store it if valid */
export async function activateLicence(key: string): Promise<boolean> {
  const normalised = normaliseKey(key);

  // 1. Check legacy hardcoded hashes first (instant, offline)
  const hash = await sha256(normalised);
  if (LEGACY_KEY_HASHES.includes(hash)) {
    try { localStorage.setItem(STORAGE_KEY, hash); } catch { /* ignore */ }
    return true;
  }

  // 2. Validate against Worker KV endpoint
  const valid = await validateKeyOnline(normalised);
  if (valid) {
    try {
      // Store as "kv:<normalisedKey>" so we know it came from KV
      localStorage.setItem(STORAGE_KEY, `kv:${normalised}`);
      localStorage.setItem(STORAGE_KEY_RAW, normalised);
    } catch { /* ignore */ }
    return true;
  }

  return false;
}

/** Clear the stored licence (for testing / reset) */
export function clearLicence(): void {
  try {
    localStorage.removeItem(STORAGE_KEY);
    localStorage.removeItem(STORAGE_KEY_RAW);
  } catch { /* ignore */ }
}

// Keep VALID_KEY_HASHES export for any other files that import it
export const VALID_KEY_HASHES: string[] = LEGACY_KEY_HASHES;
